### ISSUE TITLE
date Transformer is not applying Etc/GMT or America/New_York timezones

### ISSUE THREAD

**Issue by GoodGuyGoose** [integreat-io/integreat-transformers#2]
Timezones not applying in the following pipelines:
```
"start": [
  {
    "\\$transform": "now"
  },
  {
    "\\$transform": "date",
    "set": {
      "day": 1,
      "hour": 0,
      "minute": 0,
      "second": 0,
      "millisecond": 0
    },
    "tz": "Etc/GMT"
  }
]
```

```
"start": [
  {
    "\\$transform": "now"
  },
  {
    "\\$transform": "date",
    "set": {
      "day": 1,
      "hour": 0,
      "minute": 0,
      "second": 0,
      "millisecond": 0
    },
    "tz": "America/New_York"
  }
]
```

Highly likely that tzs are not being applied at all. In both situations "start" was in UTC format, but the value was based off local time. For example in both situations the resulting value was : `start: 2023-05-31T22:00:00.000Z`

**Comment by kjellmorten** [comment]
I have not been able to replicate this. It might have been fixed by another update, or it was related to something outside of this package. :)
